### ISSUE TITLE
Connection times out when trying to connect to UF via browser

### ISSUE THREAD

**Issue by rkain365** [CalthorpeAnalytics/urbanfootprint#6]
I created a AWS instance and ran the quickstart script which completed successfully.   When I try to access the public IP I get a time out error?  

I am running a Ubuntu 14.04 (Trusty) AMI on a t2.large instance.   I connected via Putty and ran the "quickstart" script.  It took about 15 min and at the end I received the completed dialog with the IP to access.  I confirmed that the IP listed in the session is the public IP from the AWS console.

**Comment by jalessio** [comment]
@rkain365 that could be for any number of issues. Could you provide a more detailed error report for the type of timeout you are getting? For example, if it's a network timeout connecting to the server then it could be an EC2 security group that is blocking traffic. Or is it connecting to the server and then webserver is timing out?

One way to narrow down the cause is by using telnet. Here's an example using `www.google.com`. Swap out `www.google.com` for the IP address of your EC2 instance:
```
> telnet www.google.com 80
Trying 216.58.192.4...
Connected to www.google.com.
Escape character is '^]'.
```
If you see a timeout error instead of `Connected to` then your network traffic is not even making it to your EC2 instance.

**Comment by rkain365** [comment]
It was in the Security Group.   I needed to set the inbound rules on the EC2 to allow HTTP.   By default only SSH was permitted.
